# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# Temporary disabling hooks: SKIP=flake8 git commit -m "foo"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        name: Check for files larger than 5 MB
        args: [ "--maxkb=5120" ]
      - id: end-of-file-fixer
        name: Check for a blank line at the end of scripts (auto-fixes)
        exclude: '\.Rd'
      - id: trailing-whitespace
        name: Check for trailing whitespaces (auto-fixes)
  # - repo: https://github.com/pycqa/isort # raises an error disabled for now
  #   rev: 5.11.2
  #   hooks:
  #     - id: isort
  #       name: isort (python)
  - repo: https://github.com/psf/black
    rev: 23.3.0 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        name: black - consistent Python code formatting (auto-fixes)
        language_version: python # Should be a command that runs python3.6+
  # - repo: https://github.com/pycqa/flake8
  #   rev: 6.0.0
  #   hooks:
  #     - id: flake8
  #       name: flake8 - Python linting
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.1
    hooks:
      - id: gitleaks
